[project]
name = "data-platform"
version = "0.1.0"
description = "Repository for data platform scripts and testing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "botocore==1.38.46",
    "boto3==1.38.46"
]
