name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronized
      - reopened

jobs:
  run-python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # only latest commit

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh && echo "Successfully installed uv"
          uv pip install -r pyproject.toml
          uv pip install pytest pytest-cov

      - name: Run PyTest
        run: | 
          find . -name '*.pyc' -delete
          find . -name '__pycache__' -delete
          PYTHONPATH=. pytest $(find . -type d -name '__tests__') --verbosity=3 --cache-clear -p no:warnings --cov
